@extends('hrms-layout')
@section('content')
<div class="page">
    <div class="employee-crumb"><span>HỆ THỐNG NHÂN SỰ</span><b>/</b><strong>Danh sách công việc</strong></div>
    <div style="display:flex;justify-content:space-between;align-items:end;margin-bottom:20px"><div><h1>Danh sách công việc</h1><p class="subtitle">Các nhiệm vụ được HR giao cho bạn.</p></div><span class="badge">{{ $tasks->total() }} công việc</span></div>
    <div class="card" style="margin-bottom:20px"><form method="GET" action="{{ route('employee.tasks.index') }}" style="display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:10px;align-items:end"><div class="form-group"><label for="q">Tìm theo tiêu đề</label><input class="input" id="q" name="q" value="{{ $filters['q'] ?? '' }}"></div><div class="form-group"><label for="status">Trạng thái</label><select class="select" id="status" name="status"><option value="">Tất cả</option><option value="in_progress" @selected(($filters['status'] ?? '') === 'in_progress')>Đang thực hiện</option><option value="completed" @selected(($filters['status'] ?? '') === 'completed')>Hoàn thành</option><option value="stopped" @selected(($filters['status'] ?? '') === 'stopped')>Dừng thực hiện</option></select></div><div class="form-group"><label for="due_from">Hạn từ ngày</label><input class="input" type="date" id="due_from" name="due_from" value="{{ $filters['due_from'] ?? '' }}"></div><div class="form-group"><label for="due_to">Hạn đến ngày</label><input class="input" type="date" id="due_to" name="due_to" value="{{ $filters['due_to'] ?? '' }}"></div><button class="button" type="submit">Lọc</button></form></div>
    <div class="grid grid-3"><div class="card stat"><div class="stat-label">Tổng công việc</div><div class="stat-value">{{ $tasks->total() }}</div><div class="stat-icon">☷</div></div><div class="card stat"><div class="stat-label">Đang thực hiện</div><div class="stat-value">{{ $tasks->where('status.value','in_progress')->count() }}</div><div class="stat-icon">◷</div></div><div class="card stat"><div class="stat-label">Hoàn thành</div><div class="stat-value">{{ $tasks->where('status.value','completed')->count() }}</div><div class="stat-icon">✓</div></div></div>
    <div class="card" style="margin-top:20px;padding:0;overflow:hidden"><div class="table-wrap"><table class="data-table"><thead><tr><th>Tên công việc</th><th>Người giao</th><th>Hạn hoàn thành</th><th>Trạng thái</th><th></th></tr></thead><tbody>@forelse($tasks as $task)<tr><td><strong>{{ $task->title }}</strong><br><small class="muted">{{ Str::limit($task->description,90) }}</small></td><td>{{ $task->creator->name ?? 'HR' }}</td><td>{{ $task->due_at?->format('d/m/Y H:i') ?? 'Không có hạn' }}</td><td>@if($task->status->value === 'completed')<span class="badge green">Hoàn thành</span>@elseif($task->status->value === 'in_progress')<span class="badge orange">Đang thực hiện</span>@elseif($task->status->value === 'stopped')<span class="badge red">Dừng thực hiện</span>@endif</td><td><a class="button light" href="{{ route('employee.tasks.show',$task) }}">Xem chi tiết</a></td></tr>@empty<tr><td colspan="5" class="empty">Bạn chưa được giao công việc nào.</td></tr>@endforelse</tbody></table></div></div>
    @if($tasks->hasPages())<div style="margin-top:20px">{{ $tasks->links() }}</div>@endif
</div>
@endsection
