@extends('layouts.admin')

@section('title', 'Dashboard Admin · HUIT HRMS')

@section('content')
<div class="stitch-page admin-page">
    <div class="stitch-context-row"><div class="stitch-context"><span>HỆ THỐNG QUẢN TRỊ</span><span class="stitch-context-slash">/</span><span>Tổng quan</span></div><span class="stitch-kicker">ADMIN WORKSPACE</span></div>
    <div class="hr-module-heading"><div><h1>Dashboard Admin</h1><p>Quản lý tài khoản, phân quyền và phê duyệt phiếu yêu cầu trong hệ thống.</p></div><div class="stitch-summary-icon primary"><span class="material-symbols-outlined">admin_panel_settings</span></div></div>
    <section class="stitch-summary-grid admin-summary-grid">
        @foreach($stats as $stat)
            <article class="stitch-summary-card"><div class="stitch-summary-head"><span>{{ $stat['label'] }}</span><div class="stitch-summary-icon {{ $loop->index === 2 ? 'secondary' : 'primary' }}"><span class="material-symbols-outlined">{{ ['groups', 'verified_user', 'pending_actions', 'task_alt'][$loop->index] }}</span></div></div><div class="stitch-summary-value">{{ $stat['value'] }}</div><span class="stitch-summary-caption">{{ ['Toàn bộ hệ thống', 'Đang được phép truy cập', 'Cần Admin xử lý', 'Đã có quyết định'][$loop->index] }}</span></article>
        @endforeach
    </section>
    <div class="stitch-content-grid">
        <div class="stitch-main-column">
            <section class="stitch-panel"><div class="stitch-panel-head"><div class="stitch-panel-title"><div class="stitch-panel-icon primary"><span class="material-symbols-outlined">receipt_long</span></div><div><h2>PYC gần đây</h2><p>Các yêu cầu mới nhất cần Admin theo dõi</p></div></div><a class="stitch-profile-link" href="{{ route('admin.requests') }}">Xem tất cả <span class="material-symbols-outlined">arrow_forward</span></a></div><div class="stitch-table-wrap"><table class="stitch-table"><thead><tr><th>Mã phiếu</th><th>Người gửi</th><th>Nội dung</th><th>Trạng thái</th></tr></thead><tbody>@forelse($latestRequests as $record)<tr><td><a class="stitch-request-code" href="{{ route('admin.requests.show', $record) }}">#PYC-{{ str_pad($record->id, 4, '0', STR_PAD_LEFT) }}</a></td><td>{{ $record->creator->name ?? '—' }}</td><td>{{ $record->payload['title'] ?? $record->type->value }}</td><td><span class="stitch-status-pill {{ $record->status->value === 'pending' ? 'pending' : ($record->status->value === 'rejected' ? 'rejected' : 'completed') }}">{{ ['pending' => 'Đang xử lý', 'completed' => 'Hoàn thành', 'rejected' => 'Từ chối'][$record->status->value] ?? $record->status->value }}</span></td></tr>@empty<tr><td colspan="4" class="stitch-empty">Chưa có phiếu yêu cầu.</td></tr>@endforelse</tbody></table></div></section>
            <section class="stitch-panel"><div class="stitch-panel-head"><div class="stitch-panel-title"><div class="stitch-panel-icon neutral"><span class="material-symbols-outlined">manage_accounts</span></div><div><h2>Tài khoản mới nhất</h2><p>Danh sách tài khoản trong hệ thống</p></div></div><a class="stitch-profile-link" href="{{ route('admin.accounts') }}">Quản lý tài khoản <span class="material-symbols-outlined">arrow_forward</span></a></div><div class="stitch-table-wrap"><table class="stitch-table"><thead><tr><th>Tài khoản</th><th>Vai trò</th><th>Trạng thái</th><th>Ngày tạo</th></tr></thead><tbody>@foreach($latestUsers as $account)<tr><td><div class="hr-demo-person"><span class="avatar">{{ strtoupper(substr($account->name, 0, 2)) }}</span><div><strong>{{ $account->name }}</strong><small>{{ $account->email }}</small></div></div></td><td>{{ strtoupper($account->role->value) }}</td><td><span class="stitch-status-pill {{ $account->is_active ? 'completed' : 'rejected' }}">{{ $account->is_active ? 'Hoạt động' : 'Đã khóa' }}</span></td><td class="stitch-muted">{{ $account->created_at?->format('d/m/Y') }}</td></tr>@endforeach</tbody></table></div></section>
        </div>
        <div class="stitch-side-column"><section class="stitch-panel"><div class="stitch-side-head"><div class="stitch-panel-icon primary"><span class="material-symbols-outlined">security</span></div><div><h3>Quyền quản trị</h3><span>Kiểm soát truy cập hệ thống</span></div></div><div class="stitch-key-list"><div><span>Vai trò hiện tại:</span><strong>ADMIN</strong></div><div><span>Phân quyền:</span><strong>Toàn hệ thống</strong></div><div><span>Bảo mật:</span><span class="stitch-status-pill completed">Đang bật</span></div><div><span>Phiên đăng nhập:</span><strong>Đang hoạt động</strong></div></div></section><section class="stitch-panel"><div class="stitch-side-head"><div class="stitch-panel-icon neutral"><span class="material-symbols-outlined">bolt</span></div><div><h3>Thao tác nhanh</h3><span>Truy cập các chức năng chính</span></div></div><div class="admin-quick-actions"><a class="button full" href="{{ route('admin.requests') }}"><span class="material-symbols-outlined">fact_check</span>Xử lý PYC</a><a class="button button-light full" href="{{ route('admin.accounts') }}"><span class="material-symbols-outlined">manage_accounts</span>Quản lý tài khoản</a></div></section></div>
    </div>
</div>
@endsection
