@extends('layouts.admin')

@section('content')
    @php($status = $requestModel->status->value)
    <div class="stitch-page admin-page">
        <div class="stitch-context-row"><div class="stitch-context"><span class="stitch-kicker">Admin</span><span class="stitch-context-slash">/</span><span>Phiếu yêu cầu</span><span class="stitch-context-slash">/</span><span>Chi tiết</span></div><span class="stitch-date"><span></span> Cập nhật theo thời gian thực</span></div>
        <div class="hr-module-heading"><div><h1>Chi tiết phiếu yêu cầu</h1><p>#PYC-{{ str_pad($requestModel->id, 4, '0', STR_PAD_LEFT) }} · {{ $requestModel->creator->name ?? 'Nhân viên' }}</p></div><span class="stitch-status-pill {{ $status }}">{{ $status === 'pending' ? 'Đang xử lý' : ($status === 'rejected' ? 'Từ chối' : 'Hoàn thành') }}</span></div>
        @if(session('status'))<div class="notice admin-notice"><span class="material-symbols-outlined">check_circle</span>{{ session('status') }}</div>@endif

        <div class="stitch-content-grid admin-detail-grid">
            <div class="stitch-main-column">
                <div class="stitch-panel"><div class="stitch-panel-head"><div class="stitch-panel-title"><span class="stitch-panel-icon primary"><span class="material-symbols-outlined">description</span></span><div><h2>{{ $requestModel->displayTitle() }}</h2><p>Nội dung do nhân viên gửi lên hệ thống</p></div></div></div><div class="admin-request-details">@forelse($requestModel->displayDetails() as $detail)<div class="admin-request-detail"><span>{{ $detail['label'] }}</span><p>{{ $detail['value'] }}</p></div>@empty<div class="hr-module-empty"><span class="material-symbols-outlined">description</span><strong>Phiếu chưa có nội dung chi tiết</strong><p>Không tìm thấy dữ liệu nội dung trong payload.</p></div>@endforelse</div><div class="stitch-key-list admin-detail-list"><div><span>Loại yêu cầu</span><strong>{{ $requestModel->type->value }}</strong></div><div><span>Mức độ ưu tiên</span><strong>{{ data_get($requestModel->payload, 'priority', 'low') }}</strong></div><div><span>Người gửi</span><strong>{{ $requestModel->creator->name ?? '—' }}</strong></div><div><span>Ngày gửi</span><strong>{{ $requestModel->created_at?->format('d/m/Y H:i') }}</strong></div></div></div>
                <div class="stitch-panel"><div class="stitch-panel-head"><div class="stitch-panel-title"><span class="stitch-panel-icon neutral"><span class="material-symbols-outlined">history</span></span><div><h2>Lịch sử xử lý</h2><p>Các mốc cập nhật của phiếu</p></div></div></div>@if($requestModel->processed_at)<div class="admin-audit-row"><span class="material-symbols-outlined">check_circle</span><div><strong>{{ $requestModel->processed_at->format('d/m/Y H:i') }}</strong><p>{{ $requestModel->processing_note ?: 'Đã cập nhật trạng thái.' }}</p></div></div>@else<div class="hr-module-empty"><span class="material-symbols-outlined">pending_actions</span><strong>Chưa có lịch sử xử lý</strong><p>Phiếu này đang chờ Admin đưa ra quyết định.</p></div>@endif</div>
            </div>
            <div class="stitch-side-column">
                <div class="stitch-panel"><div class="stitch-side-head"><span class="material-symbols-outlined">rule</span><div><h3>Quyết định xử lý</h3><span>Admin workspace</span></div></div>@if($status === 'pending')<form method="POST" action="{{ route('admin.requests.process', $requestModel) }}">@csrf @method('PUT')<div class="form-group"><label>Trạng thái mới</label><select class="select admin-form-control" name="status"><option value="rejected">Từ chối</option><option value="completed">Hoàn thành</option></select></div><div class="form-group"><label>Ghi chú xử lý *</label><textarea class="input textarea admin-form-control" name="processing_note" required></textarea></div><button class="button full" type="submit"><span class="material-symbols-outlined">task_alt</span>Xác nhận xử lý</button></form>@else<div class="admin-complete-state"><span class="material-symbols-outlined">verified</span><strong>Phiếu đã được xử lý</strong><p>Không thể xử lý lại phiếu này.</p></div>@endif<a class="modal-secondary-action" href="{{ route('admin.requests') }}"><span class="material-symbols-outlined">arrow_back</span>Quay lại danh sách</a></div>
            </div>
        </div>
    </div>
@endsection
