@extends('layouts.hr')

@section('content')
    <div class="stitch-page hr-module-page">
        <div class="stitch-context-row"><div class="stitch-context"><span class="stitch-kicker">CỔNG NHÂN SỰ</span><span class="stitch-context-slash">/</span><span>Dashboard</span></div><span class="stitch-kicker">HR WORKSPACE</span></div>
        <div class="hr-module-heading"><div><h1>Dashboard HR</h1><p>Tổng quan tình hình nhân sự và hoạt động hôm nay.</p></div><div class="stitch-summary-icon primary"><span class="material-symbols-outlined">dashboard</span></div></div>
        @if($attendance?->check_in_at && !$attendance?->check_out_at)
            <form method="POST" action="{{ route('attendance.check-out') }}" class="stitch-checkout-form hr-dashboard-checkout-bar">
                @csrf
                <div><strong>Ca làm việc đang mở</strong><span>Check-in lúc {{ $attendance->check_in_at->format('H:i') }}</span></div>
                <button class="button" type="submit"><span class="material-symbols-outlined">logout</span>Check-out</button>
            </form>
        @endif

        <div class="stitch-summary-grid hr-module-summary">
            <div class="stitch-summary-card"><div class="stitch-summary-head"><span>Tổng nhân viên</span><span class="stitch-summary-icon"><span class="material-symbols-outlined">groups</span></span></div><div class="stitch-summary-value">{{ $totalEmployees }} <small>hồ sơ</small></div><div class="stitch-summary-caption">Trong hệ thống</div></div>
            <div class="stitch-summary-card"><div class="stitch-summary-head"><span>Đang làm việc</span><span class="stitch-summary-icon"><span class="material-symbols-outlined">verified_user</span></span></div><div class="stitch-summary-value">{{ $activeEmployees }} <small>nhân viên</small></div><div class="stitch-summary-caption">Tài khoản hoạt động</div></div>
            <div class="stitch-summary-card"><div class="stitch-summary-head"><span>PYC chờ xử lý</span><span class="stitch-summary-icon secondary"><span class="material-symbols-outlined">pending_actions</span></span></div><div class="stitch-summary-value">{{ $pendingRequests }} <small>phiếu</small></div><div class="stitch-summary-caption">Cần HR phản hồi</div></div>
            <div class="stitch-summary-card"><div class="stitch-summary-head"><span>Chưa check-out</span><span class="stitch-summary-icon secondary"><span class="material-symbols-outlined">schedule</span></span></div><div class="stitch-summary-value">{{ $notCheckedOut }} <small>trường hợp</small></div><div class="stitch-summary-caption">{{ $lateCount }} trường hợp đi muộn hôm nay</div></div>
        </div>
        <div class="stitch-content-grid">
            <div class="stitch-main-column">
                <section class="stitch-panel"><div class="stitch-panel-head"><div class="stitch-panel-title"><span class="stitch-panel-icon primary"><span class="material-symbols-outlined">schedule</span></span><div><h2>Chấm công hôm nay</h2><p>Dữ liệu nhân sự đã check-in trong ngày</p></div></div><a class="stitch-profile-link" href="{{ route('hr.attendance.index') }}">Xem tất cả <span class="material-symbols-outlined">arrow_forward</span></a></div><div class="stitch-table-wrap"><table class="stitch-table"><thead><tr><th>Mã nhân viên</th><th>Họ tên</th><th>Chức vụ</th><th>Check-in</th><th>Check-out</th><th>Trạng thái</th></tr></thead><tbody>@forelse($todayAttendances as $attendance)<tr><td><strong>{{ $attendance->employee?->employee_code ?? '—' }}</strong></td><td>{{ $attendance->employee?->full_name ?? '—' }}</td><td>{{ $attendance->employee?->position?->name ?? '—' }}</td><td>{{ $attendance->check_in_at?->format('H:i') ?? '—' }}</td><td>{{ $attendance->check_out_at?->format('H:i') ?? 'Chưa check-out' }}</td><td><span class="stitch-status-pill {{ $attendance->check_out_at ? 'completed' : 'working' }}">{{ $attendance->check_out_at ? 'Đã đủ ca' : 'Đang làm việc' }}</span></td></tr>@empty<tr><td colspan="6" class="stitch-empty">Chưa có dữ liệu chấm công hôm nay.</td></tr>@endforelse</tbody></table></div></section>
                <section class="stitch-panel"><div class="stitch-panel-head"><div class="stitch-panel-title"><span class="stitch-panel-icon neutral"><span class="material-symbols-outlined">checklist</span></span><div><h2>Công việc gần đây</h2><p>Nhiệm vụ HR đang theo dõi</p></div></div><a class="stitch-profile-link" href="{{ route('hr.tasks') }}">Xem công việc <span class="material-symbols-outlined">arrow_forward</span></a></div><div class="stitch-table-wrap"><table class="stitch-table"><thead><tr><th>Công việc</th><th>Người thực hiện</th><th>Hạn hoàn thành</th><th>Trạng thái</th></tr></thead><tbody>@forelse($recentTasks as $task)<tr><td><strong>{{ $task->title }}</strong></td><td>{{ $task->assignee?->full_name ?? '—' }}</td><td>{{ $task->due_at?->format('d/m/Y') ?? '—' }}</td><td><span class="stitch-status-pill {{ $task->status->value }}">{{ ['in_progress' => 'Đang thực hiện', 'completed' => 'Hoàn thành', 'stopped' => 'Đã dừng'][$task->status->value] ?? $task->status->value }}</span></td></tr>@empty<tr><td colspan="4" class="stitch-empty">Chưa có công việc.</td></tr>@endforelse</tbody></table></div></section>
            </div>
            <div class="stitch-side-column"><section class="stitch-panel"><div class="stitch-side-head"><span class="material-symbols-outlined">bolt</span><div><h3>Việc cần xử lý</h3><span>Tổng hợp từ database</span></div></div><div class="stitch-key-list"><div><span>Phiếu yêu cầu</span><strong class="secondary-text">{{ $pendingRequests }} đang chờ</strong></div><div><span>Hồ sơ tuyển dụng</span><strong>{{ $openRecruitment }} đang mở</strong></div><div><span>Đi muộn hôm nay</span><strong class="secondary-text">{{ $lateCount }} trường hợp</strong></div><div><span>Chưa check-out</span><strong>{{ $notCheckedOut }} trường hợp</strong></div></div><div class="stitch-info-note"><span class="material-symbols-outlined">info</span><p>Số liệu được tính trực tiếp từ hồ sơ nhân viên, chấm công, công việc và phiếu yêu cầu.</p></div></section><section class="stitch-panel"><div class="stitch-side-head"><span class="material-symbols-outlined">link</span><div><h3>Truy cập nhanh</h3><span>Các chức năng HR</span></div></div><div class="admin-quick-actions"><a class="button full" href="{{ route('hr.employees') }}"><span class="material-symbols-outlined">groups</span>Quản lý nhân viên</a><a class="button button-light full" href="{{ route('hr.requests') }}"><span class="material-symbols-outlined">receipt_long</span>Xem phiếu yêu cầu</a></div></section></div>
        </div>
        @if(($show ?? null) === 'checkin')
            <div class="modal-backdrop"><div class="modal"><div class="modal-icon"><span class="material-symbols-outlined">how_to_reg</span></div><span class="badge">HỆ THỐNG CHẤM CÔNG HUIT</span><h2>Chấm công đầu ngày</h2><p>Xin chào, {{ auth()->user()->name }}<br>Bạn chưa Check-in hôm nay. Vui lòng Check-in trước khi bắt đầu làm việc.</p><div class="modal-info"><div class="row"><span class="row-label">Mã nhân viên</span><strong>{{ $employee?->employee_code ?? '—' }}</strong></div><div class="row"><span class="row-label">Chức vụ</span><strong>{{ $employee?->position?->name ?? '—' }}</strong></div><div class="row"><span class="row-label">Phòng ban</span><strong>{{ $employee?->department?->name ?? '—' }}</strong></div><div class="row"><span class="row-label">Giờ hiện tại</span><strong>{{ now()->format('H:i') }}</strong></div></div><form method="POST" action="{{ route('attendance.check-in.store') }}">@csrf<button class="button full" type="submit"><span class="material-symbols-outlined">login</span>Check-in ngay</button></form><form method="POST" action="{{ route('logout') }}" style="margin-top:12px">@csrf<button class="stitch-modal-logout" type="submit"><span class="material-symbols-outlined">logout</span>Đăng xuất</button></form></div></div>
        @elseif(($show ?? null) === 'checkout-confirmation')
            <div class="modal-backdrop"><div class="modal attendance-modal"><div class="modal-icon"><span class="material-symbols-outlined">logout</span></div><span class="badge">XÁC NHẬN KẾT THÚC CA</span><h2>Bạn chưa Check-out</h2><p>Ca làm việc hôm nay vẫn đang mở. Vui lòng Check-out trước khi đăng xuất.</p><div class="modal-info"><div class="row"><span class="row-label">Giờ Check-in</span><strong>{{ $attendance?->check_in_at?->format('H:i') ?? '—' }}</strong></div><div class="row"><span class="row-label">Trạng thái</span><strong>Đang làm việc</strong></div></div><form method="POST" action="{{ route('attendance.check-out') }}">@csrf<button class="button full" type="submit"><span class="material-symbols-outlined">check_circle</span>Check-out và tiếp tục</button></form><a class="modal-secondary-action" href="{{ route('hr.home') }}">Quay lại Dashboard</a></div></div>
        @elseif(($show ?? null) === 'checkin-success')
            <div class="modal-backdrop"><div class="modal success"><div class="modal-icon"><span class="material-symbols-outlined">check</span></div><h2>Check-in thành công</h2><p>Bạn đã Check-in lúc {{ now()->format('H:i') }}.</p><a class="button full" href="{{ route('hr.home') }}">Vào Dashboard</a></div></div>
        @elseif(($show ?? null) === 'checkout-success')
            <div class="modal-backdrop"><div class="modal success"><div class="modal-icon"><span class="material-symbols-outlined">check</span></div><h2>Check-out thành công</h2><p>Ca làm việc hôm nay đã được kết thúc. Bạn có thể đăng xuất.</p><form method="POST" action="{{ route('logout') }}">@csrf<button class="button full" type="submit"><span class="material-symbols-outlined">logout</span>Đăng xuất</button></form><a class="button light full" style="margin-top:12px" href="{{ route('hr.home') }}">Về Dashboard</a></div></div>
        @endif
    </div>
@endsection
